### ISSUE TITLE
Can't like someone

### ISSUE THREAD

**Issue by gnutix** [tranhungt/okcupidjs#18]
I'm trying to know who's liking me (without paying for it). My idea is : like everyone in my search criterion, check the "mutual likes" page, then unlike those that have been liked. Here's the code I've written for now:

```
var OKCupid = require('okcupidjs');
var okc = new OKCupid();

okc.login(/* my username */, /* my password */, function() {
    okc.search({ /* my search criterion */}, function(err, res, users) {
        users.data.forEach(function(user) {
            if (!user.inactive) {
                console.log(user.username);
                okc.like(user.userid, function (err, res, body) {
                    console.log(err);
                    console.log(body);
                });
            }
        });
    });
});
```

The output is : 
```
someone_in_my_search_criteria_username
null
{ error: { type: 'OAuthError', message: 'required access_token missing' } }
```

I've tried adding again the `okc.login` around the `okc.like` call, but didn't changed a thing.
Any idea why ?

**Comment by tranhungt** [comment]
Curious, are you on the latest version 1.1.0?

**Comment by xmclark** [comment]
I'm trying to recollect how the authentication works. If my memory serves me right, then I believe the OKC API sticks the OAuth token in the response header, and the Request module should retain the token when sending additional requests. The newer OKC API uses OAuth, and the search feature uses it. I was able to test search, but it's possible there may be another issue. 

@tranhungt have you tested search at all? I ask because I haven't heard from anyone else that it works for them.

**Comment by xmclark** [comment]
@gnutix So I just tried running some very similar code on my machine and search, like, and unlike do as expected with no oauth errors.

Is it possibly you may have type your credentials in wrong? I noticed earlier today that I was getting a false positive on login, so when I tried making calls, I was getting errors. That may be a bug that has to be written up.

**Comment by gnutix** [comment]
So silly of me... indeed it was a bad case for the password. It's working now, thanks! :)
